### PR TITLE
Review Annotations

### PR DESCRIPTION
**Pull request by shantanusinghal**
I'm half-way done with the annotations but before proceeding further I thought I'd share all the assumptions I've made and resolve any conflicting decisions before moving forward.

### Marked
- peanut used as a metaphor [04]
- ’s version of poutine [09]
- Generic Terms
   - seafood [22]
   - curry [31]
   - sauce [20]
   - fruit used by itself [22]
   - veggie used as vegetable [22] <sup>1</sup>
- Typos
   - “choy suey” instead of chop-suey [25]
   - “dan fan noodle” instead of dan-dan-noodle [42]

### Skipped
- vegetarian used by itself [07] <sup>3</sup>
- vanilla used by itself [23] **<sup>7</sup>**
- veggie used as vegetable [19] <sup>1</sup>
- gluten-free and vegan used by themselves [09, 14]
- **Adjectives** like
    - place-name in PLACE_NAME + FOOD_ITEM formats (eg. Montreal sandwich)
    - smoked in “smoked meat” [03, 16]
    - instant in “instant noodles” [20]
    - tower in “onion ring tower” [23]
    - organic in “organic cream cheese” [28]
    - grilled in “grilled pork banh mi” [29]
    - fried 
        - in “fried rice” [31] <sup>2</sup>
        - in “fried __ fish” [31]
    - homemade 
        - in “homemade ice cream” [37]
        - in “homemade chilly oil” [42]
    - sweet in “sweet potato wedges” [38]
    - pink in “pink dragon roll” [39]
    - fresh in “fresh juices” [40]
    - spicy 
        - in “spicy peanut sauce” [42]
        - in “Spicy Horse Tartare” [46]
        - 
    - chilly in “chilly oil” [42]
    - bubble in “bubble tea” [44] 
    - ice in “ice tea” [44] <sup>4</sup>
    - milk in “milk tea” [44] <sup>5</sup>
    - roasted 
        - in “roasted oolong milk tea” [44]
        - in “roasted bone marrow” [46]
    - supernova in “supernova kumquat lemonade” [44]
    - cured in “cured bacon” [47]
    - house cured 
        - in “house cured bacon” [47]
        - in “house cured peameal bacon” [47]
        - in “House Cured Meat” [46]
        - 
    - griddled in “griddled __ potatoes” [47]
    - crispy in “crispy ___ potatoes” [47]
    - poached in “poached eggs” [
- Classification terms like [“brunch”, “breakfast”, “lunch”, “salty”, “X-food”<sup>6</sup>, “treats”, “vegan”, “gluten”, “dessert”]

---

<sup>1</sup> veggie can mean both vegetable (valid-case) and vegetarian (invalid-case)
<sup>2</sup> in 31.txt I’ve annotated “basil fried rice” but not it’s subset “fried rice”
<sup>3</sup> but included when used like [“vegetarian platter”]
<sup>4</sup> but I’ve included “peach ice tea” because the otherwise in-valid term ice (as in iced) is trapped between peach and tea which are both valid terms, both individually and together.
<sup>5</sup> but I’ve annotated milk separately and “oolong milk tea” is also tagged because oolong is a specific enough descriptor.
<sup>6</sup> for example "chinese food", "vietnamese food", etc.
**<sup>7</sup> I'm definitely leaning towards including this one!**

### CODE REVIEW

**Comment by shantanusinghal** [comment]
BTW this is the list of text files without any mentions of a food item 

`0-list [6, 10, 13, 17, 24, 26, 30, 36, 45, 48]`

**Comment by yogeshchellappa** [comment]
I have added sauce and veggie because it has been used a lot, as food. 
"I loved the sauce", "I had  a veggie roll" and so on. 

We could add vanilla.

Items like iced tea, ice by itself is not a dish. Hence let's add "Iced tea" as a whole. Same with items such as "Home cured bacon". This can be split as "bacon" and "Home cured bacon"

**Comment by sukanyavenkataraman** [comment]
I've been marking sauce as well. The heuristic I used was - If I see this
ngram separately, as the only ngram to classify, would I label it as food
or not. So like Yogesh had mentioned, you can keep the organic in "organic
cream cheese". Also, I kept the place name in most places because if we see
"New York Cheesecake", we will think that it's a food item.

**Comment by shantanusinghal** [comment]
Thanks for that feedback guys. I will fix the annotated reviews to include words like “vanilla” and “sauce”. 

I like your heuristic Sukanya and, its similar to what I’ve been using myself but, while judging the 1-grams like spicy, grilled, cured, iced, organic... in isolation I didn’t find them to satisfy our definition of a food item. And, as far as complete dish names like new york cheesecake and philly cheese steak go, I was trying to follow the professor’s advice about not including adjectives and I coudln't justify it to myself why they should be treated differently from say "fresh whipped creme" which I would have annotated as `fresh whipped <creme/>`

**Pull request merged**
